version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update -y
            apt-get install cmake -y
            git submodule update --init
      - run:
          name: Build teesmash with cmake in Release mode
          command: |
            mkdir -p release
            cd release
            env CFLAGS="-Wdeclaration-after-statement -Werror" CXXFLAGS="-Werror" cmake -Werror=dev -DDOWNLOAD_GTEST=ON ..
            make everything
            make run_tests
            ./teesmash_srv shutdown
      - run:
          name: Build teeworlds with cmake in Debug mode
          command: |
            mkdir -p debug
            cd debug
            env CFLAGS="-Wdeclaration-after-statement -Werror" CXXFLAGS="-Werror" cmake -Werror=dev -DDOWNLOAD_GTEST=ON -DDEV=ON ..
            make everything
            make run_tests
            ./teesmahs_srv shutdown
